---
- name: Copy `vagrant` user package
  ansible.builtin.copy:
    src: files/uk.ac.cam.ccdc.mac-vagrant-user.dmg
    dest: "{{ remote_macos_user_image }}"

- name: Mount user package
  ansible.builtin.command: |
    mkdir -p "{{ remote_macos_user_mountpoint }}"
    hdiutil attach "{{ remote_macos_user_image }}" -mountpoint "{{ remote_macos_user_mountpoint }}"

- name: Validate code signature on `vagrant` user package
  ansible.builtin.command: codesign -vvv {{ remote_macos_user_package }}

- name: Create `vagrant` user
  ansible.builtin.command: sudo installer -pkg {{ remote_macos_user_package }} -target /
  become: true

- name: Mount user package
  ansible.builtin.command: |
    hdiutil detach "{{ remote_macos_user_image }}"
    rmdir "{{ remote_macos_user_mountpoint }}"

- name: Copy SetupAssistant preferences for `vagrant` user
  ansible.builtin.copy:
    src: files/com.apple.SetupAssistant.{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.plist
    dest: "/Users/vagrant/Library/Preferences/com.apple.SetupAssistant.plist"
    owner: vagrant
    mode: "0600"

- name: Disable Sleep
  ansible.builtin.command: "{{ item }}"
  with_items:
    - systemsetup -setsleep Never
    - systemsetup -setharddisksleep Never
    - systemsetup -setcomputersleep Never
    - systemsetup -setdisplaysleep Never
  changed_when: false
  become: true

- name: Additional cleanup for never sleep mode
  ansible.builtin.include_role:
    name: feffi.macos-standby
  vars:
    standby_delay: false  # noqa: var-naming[no-role-prefix]
    hibernate_mode: 0  # noqa: var-naming[no-role-prefix]
    remove_sleepimage: true  # noqa: var-naming[no-role-prefix]

- name: Ensure homebrew is installed
  ansible.builtin.include_role:
    name: geerlingguy.homebrew
