---
- name: Set OS-specific variables for {{ ansible_os_family }}-{{ ansible_distribution }}-{{ ansible_distribution_major_version }}
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "vars/{{ ansible_os_family }}-{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yaml"
        - "vars/{{ ansible_os_family }}-{{ ansible_distribution }}.yaml"
        # This is to allow to distinguish between Windows-Server/Windows-Client
        - "vars/{{ ansible_os_family }}-{{ ansible_facts.os_installation_type }}.yaml"
        - "vars/{{ ansible_os_family }}.yaml"
        - "vars/{{ ansible_system }}.yaml"
      skip: true
  tags: vars

- name: Execute tasks for {{ ansible_os_family }} ({{ ansible_distribution }} {{ ansible_distribution_major_version }})
  ansible.builtin.include_tasks: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_os_family }}-{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yaml"
        - "{{ ansible_os_family }}-{{ ansible_distribution }}.yaml"
        # This is to allow to distinguish between Windows-Server/Windows-Client
        - "{{ ansible_os_family }}-{{ ansible_facts.os_installation_type }}.yaml"
        - "{{ ansible_os_family }}.yaml"
        - "{{ ansible_system }}.yaml"
