---
- name: Get list of users and user templates
  ansible.builtin.find:
    depth: 1
    path:
      - /System/Library/User Template
      - /Users
    file_type: directory
  register: users

- name: Ensure preferences path exists for each user
  ansible.builtin.file:
    path: "{{ user.path }}/Library/Preferences"
    state: directory
    owner: "{{ user.path | basename }}"
    mode: 0600
  loop: "{{ users.files }}"
  loop_control:
    loop_var: user
  become: true
  when: "'/Users/' in user.path and '/Users/Shared' not in user.path"

- name: Debug preferences file owner
  ansible.builtin.debug:
    msg: "{{ user.path | regex_search('/Users/(?P<name>.*)', '\\g<name>') | default(root)"
  loop: "{{ users.files }}"
  loop_control:
    loop_var: user

- name: Copy SetupAssistant preferences
  ansible.builtin.copy:
    src: files/com.apple.SetupAssistant.{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.plist
    dest: "{{ user.path }}/Library/Preferences/com.apple.SetupAssistant.plist"
    owner: "{{ user.path | regex_search('/Users/(?P<name>.*)', '\\g<name>') | default(root)"
    mode: "0600"
  loop: "{{ users.files }}"
  loop_control:
    loop_var: user
  become: true
  when: "'/Users/Shared' not in user.path"

- name: Disable Setup Assistant screens
  ansible.builtin.shell: |
    /usr/bin/defaults write {{ spec.0.path }}/Library/Preferences/com.apple.SetupAssistant \
      {{ spec.1.pref_name }} {{ spec.1.pref_value }}
  loop: "{{ users.files | product(setup_assistant_preferences) | list }}"
  loop_control:
    loop_var: spec
  when: "'/Users/Shared' not in spec.0.path"
  become: true
