---
- name: Set up passwordless sudo for {{ sudo_group }}
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%{{ sudo_group }}'
    line: '%{{ sudo_group }} ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'
  become: true
